In [143]:
import os
import pandas as pd
from tqdm import tqdm

In [144]:
OUT_PATH = 'nodes'
SCHEMAS = 'node_template/submission_case_template.tsv'

In [145]:
#read the case node header
case_node = pd.read_csv(SCHEMAS, sep = '\t')
case_node.drop(index=case_node.index[0], 
        axis=0, 
        inplace=True)
case_node

Empty DataFrame
Columns: [*type, project_id, *submitter_id, *studies.submitter_id, actarm, ah_hosp, ah_hosp_num, aki_status, bari_surgery, cohort, consent_type, days_180_aki, days_180_survival, days_90_aki, days_90_survival, days_to_aki, days_to_consent, days_to_death, index_date, inf_cnst_sign_dt, rct_meld_strata, study_site, vital_status]
Index: []

[0 rows x 23 columns]

In [146]:
enrollment_pd = pd.read_csv('csv_datasets/ENROLLMENT_INFO.csv')
enrollment_pd

,usubjid,site,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,participant,init,enrollcat___1,enrollcat___2,obs_arm,enrollobsdat,dna_allow,hd_to_ah,rct_meld_strata,enrollrctdat,dna_allow_rct,enrollment_informati_v_0,visitnd
0,11001,Cleveland Clinic,Enrollment & Demographics,NaN,NaN,NaN,KER,Observational Study,NaN,CONTROL: Healthy donor,5/21/2019,NaN,NaN,NaN,NaN,NaN,Complete,NaN
1,11002,Cleveland Clinic,Enrollment & Demographics,NaN,NaN,NaN,AR,Observational Study,NaN,CONTROL: Healthy donor,5/21/2019,NaN,NaN,NaN,NaN,NaN,Complete,NaN
2,11003,Cleveland Clinic,Enrollment & Demographics,NaN,NaN,NaN,KJB,Observational Study,NaN,CASE: Heavy drinker with alcoholic hepatitis,5/24/2019,NaN,NaN,NaN,NaN,NaN,Complete,NaN
3,11004,Cleveland Clinic,Enrollment & Demographics,NaN,NaN,NaN,J-D,Observational Study,NaN,CONTROL: Healthy donor,6/4/2019,NaN,NaN,NaN,NaN,NaN,Complete,NaN
4,11006,Cleveland Clinic,Enrollment & Demographics,NaN,NaN,NaN,J-A,Observational Study,NaN,CASE: Heavy drinker with alcoholic hepatitis,6/7/2019,NaN,NaN,NaN,NaN,NaN,Complete,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,81149,Virginia Commonwealth University,Enrollment & Demographics,NaN,NaN,81149.0,NaN,Observational Study,NaN,CONTROL: Heavy drinker without alcoholic hepat...,8/26/2022,Yes,NaN,NaN,NaN,NaN,Complete,NaN
898,81150,Virginia Commonwealth University,Enrollment & Demographics,NaN,NaN,81150.0,NaN,Observational Study,NaN,CONTROL: Heavy drinker without alcoholic hepat...,8/31/2022,Yes,NaN,NaN,NaN,NaN,Complete,NaN
899,81151,Virginia Commonwealth University,Enrollment & Demographics,NaN,NaN,81151.0,NaN,Observational Study,NaN,CASE: Heavy drinker with alcoholic hepatitis,9/14/2022,Yes,NaN,NaN,NaN,NaN,Complete,NaN
900,81152,Virginia Commonwealth University,Enrollment & Demographics,NaN,NaN,81152.0,NaN,Observational Study,NaN,CASE: Heavy drinker with alcoholic hepatitis,9/16/2022,Yes,NaN,NaN,NaN,NaN,Complete,NaN
901,81153,Virginia Commonwealth University,Enrollment & Demographics,NaN,NaN,81153.0,NaN,Observational Study,NaN,CONTROL: Heavy drinker without alcoholic hepat...,9/21/2022,Yes,NaN,NaN,NaN,NaN,Complete,NaN

In [147]:
vital_aki_pd = pd.read_csv('csv_datasets/ARDaC_Mortality_and_AKI_2022-10-24.csv')
vital_aki_pd

,usubjid,vital_status,last_contact_date,death_date,acute_kidney_injury,aki_date
0,11001,alive,05/21/2019,NaN,unknown,NaN
1,11002,alive,05/21/2019,NaN,unknown,NaN
2,11003,alive,01/27/2020,NaN,unknown,NaN
3,11004,alive,06/04/2019,NaN,unknown,NaN
4,11006,dead,09/15/2019,2019-09-15,unknown,NaN
...,...,...,...,...,...,...
915,81152,alive,10/17/2022,NaN,unknown,NaN
916,81153,alive,10/17/2022,NaN,unknown,NaN
917,81154,alive,10/17/2022,NaN,unknown,NaN
918,81155,alive,10/17/2022,NaN,unknown,NaN
919,81156,alive,10/17/2022,NaN,unknown,NaN

In [148]:
randomization_pd = pd.read_csv('csv_datasets/RANDOMIZATION.csv')
randomization_pd

# s = list(randomization_pd.loc[randomization_pd['usubjid'] == 61035, 'rct_arm'])
# s

,usubjid,site,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,rct_arm,randomization_complete,visitnd,contrameth,tsprenatoth,...,pregoutcmcm,birthweight,bnotes,invest_name,invest_specialty,invest_address,invest_phone,invest_fax,preg_sourcesig,preg_sourcesig_phys
0,11055,Cleveland Clinic,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11058,Cleveland Clinic,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11066,Cleveland Clinic,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11067,Cleveland Clinic,RCT Randomization,NaN,NaN,Anakinra + Zinc,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11071,Cleveland Clinic,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,81077,Virginia Commonwealth University,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,81080,Virginia Commonwealth University,RCT Randomization,NaN,NaN,Anakinra + Zinc,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,81091,Virginia Commonwealth University,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,81096,Virginia Commonwealth University,RCT Randomization,NaN,NaN,Anakinra + Zinc,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,81108,Virginia Commonwealth University,RCT Randomization,NaN,NaN,Prednisone,Complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
from datetime import datetime

def parse_date(text):
    for fmt in ('%Y-%m-%d', '%m.%d.%Y', '%m/%d/%Y'):
        try:
            date = datetime.strptime(text, fmt).date()
            return date.strftime("%Y-%m-%d")
        except ValueError:
            pass
    raise ValueError('no valid date format found')

def days_between(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)



def calculate_vital(vital_aki_pd, index_date, enrollment_row):
    dead_row = vital_aki_pd.loc[vital_aki_pd['usubjid'] == enrollment_row.usubjid]

    
    #if a case do not have a matched vital status record
    if dead_row.empty:
        vital_status = 'Unknown'
        days_90_survival = 'Unknown'
        days_180_survival = 'Unknown'
        days_to_death = None
        return vital_status, days_to_death, days_90_survival, days_180_survival
        
    vital_status = dead_row['vital_status'].item()
#     print("vital_status: ", vital_status)
#     print("type(vital_status): ", type(vital_status))
    #reformat the date
    
    index_date = parse_date(index_date)
    
    if vital_status == 'alive':
        days_to_death = None
        contact_date =  parse_date(dead_row['last_contact_date'].item())
        
#         print("contact_date: ", contact_date)
#         print("type(contact_date): ", type(contact_date))
        
        alive_days = days_between(index_date, contact_date)
        
        if alive_days <= 90:
            days_90_survival = 'Unknown'
        elif 90 < alive_days:
            days_90_survival = 'alive'
        
        if alive_days <= 180:
            days_180_survival = 'Unknown'
        elif 180 < alive_days:
            days_180_survival = 'alive'
            
        
        
    elif vital_status == 'dead':  
        death_date = parse_date(dead_row['death_date'].item())
        days_to_death = days_between(index_date, death_date)
        if days_to_death <= 90:
            days_90_survival = 'dead'
        elif 90 < days_to_death:
            days_90_survival = 'alive'
            
        if days_to_death <= 180:
            days_180_survival = 'dead'
        elif 180 < days_to_death:
            days_180_survival = 'alive'
    else:
        vital_status = 'Unknown'
        days_90_survival = 'Unknown'
        days_180_survival = 'Unknown'
        days_to_death = None
        
    return vital_status, days_to_death, days_90_survival, days_180_survival

def calculate_aki(vital_aki_pd, index_date, enrollment_row):
    aki_row = vital_aki_pd.loc[vital_aki_pd['usubjid'] == enrollment_row.usubjid]
    
    #if a case do not have a matched aki status record
    if aki_row.empty:
        aki_status = 'Unknown'
        days_90_aki = 'Unknown'
        days_180_aki = 'Unknown'
        days_to_aki = None
        return aki_status, days_to_aki, days_90_aki, days_180_aki
    
    aki_status = aki_row['acute_kidney_injury'].item()
    
    #reformat the date
    index_date = parse_date(index_date)
    
    
    if aki_status == 'no':
        days_to_aki = None
        contact_date =  parse_date(aki_row['last_contact_date'].item())
        alive_days = days_between(index_date, contact_date)
        
        if alive_days <= 90:
            days_90_aki = 'Unknown'
        elif 90 < alive_days:
            days_90_aki = 'No'
        
        if alive_days <= 180:
            days_180_aki = 'Unknown'
        elif 180 < alive_days:
            days_180_aki = 'No'
            
    elif aki_status == 'yes':  
        aki_date = aki_row['aki_date'].item()
        
        if aki_date==aki_date: #aki_date is not NaN
            aki_date = parse_date(aki_row['aki_date'].item())
        else:                  #aki_date is NaN, use Carla's email date: 2022-10-24
            aki_date = "2022-10-24"
            
        days_to_aki = days_between(index_date, aki_date)
        if days_to_aki <= 90:
            days_90_aki = 'Yes'
        elif 90 < days_to_aki:
            days_90_aki = 'No'
            
        if days_to_aki <= 180:
            days_180_aki = 'Yes'
        elif 180 < days_to_death:
            days_180_aki = 'No'
    else:
        aki_status = 'Unknown'
        days_90_aki = 'Unknown'
        days_180_aki = 'Unknown'
        days_to_aki = None
        
    return aki_status, days_to_aki, days_90_aki, days_180_aki

In [150]:
for index,row in tqdm(enrollment_pd.iterrows(),total=enrollment_pd.shape[0],desc="process Case node"):
    #general properies for both observation and clinical trial study
    case_type = 'case'
    project_id = 'ardac-p1031'
    actarm = ' '
    ah_hosp = ' '
    ah_hosp_num = ' '
    bari_surgery = ' '
    consent_type = ' '
    days_to_consent = ' '
    index_date = ' '
    inf_cnst_sign_dt = ' '
    rct_meld_strata = ' '
    study_site = row.site
    index_date = 'Study Enrollment'
    
    #seperate the observation and clinical trial study.
    #If one patient attend both study, there will be two record for each patient
    if row.enrollcat___1 == 'Observational Study':
        studies_submitter_id = 'obs'
        submitter_id = str(row.usubjid)+'_'+studies_submitter_id
        cohort = row.obs_arm
        
        vital_status, days_to_death, days_90_survival, days_180_survival = calculate_vital(vital_aki_pd, row.enrollobsdat, row)
        aki_status, days_to_aki, days_90_aki, days_180_aki = calculate_aki(vital_aki_pd, row.enrollobsdat, row)
        #write the case node data
        case_node.loc[len(case_node.index)] = [case_type, 
                                               project_id, 
                                               submitter_id, 
                                               studies_submitter_id,
                                               actarm,
                                               ah_hosp,
                                               ah_hosp_num,
                                               aki_status,
                                               bari_surgery,
                                               cohort,
                                               consent_type,
                                               days_180_aki,
                                               days_180_survival,
                                               days_90_aki,
                                               days_90_survival,
                                               days_to_aki,
                                               days_to_consent,
                                               days_to_death,
                                               index_date,
                                               inf_cnst_sign_dt,
                                               rct_meld_strata,
                                               study_site,
                                               vital_status]
    
    if row.enrollcat___2 == 'Clinical Trial':
        studies_submitter_id = 'clinical'
        submitter_id = str(row.usubjid)+'_'+studies_submitter_id
        rct_meld_strata = row.rct_meld_strata
        cohort = ' '
        vital_status, days_to_death, days_90_survival, days_180_survival = calculate_vital(vital_aki_pd, row.enrollrctdat, row)
        aki_status, days_to_aki, days_90_aki, days_180_aki = calculate_aki(vital_aki_pd, row.enrollrctdat, row)

        randomization_pd_row= randomization_pd.loc[randomization_pd['usubjid'] == row.usubjid]
        
        if len(randomization_pd_row) != 0:
            actarm = randomization_pd_row["rct_arm"].item()
        #write the case node data
        case_node.loc[len(case_node.index)] = [case_type, 
                                               project_id, 
                                               submitter_id, 
                                               studies_submitter_id,
                                               actarm,
                                               ah_hosp,
                                               ah_hosp_num,
                                               aki_status,
                                               bari_surgery,
                                               cohort,
                                               consent_type,
                                               days_180_aki,
                                               days_180_survival,
                                               days_90_aki,
                                               days_90_survival,
                                               days_to_aki,
                                               days_to_consent,
                                               days_to_death,
                                               index_date,
                                               inf_cnst_sign_dt,
                                               rct_meld_strata,
                                               study_site,
                                               vital_status]

process Case node:  13%|██▋                  | 113/902 [00:00<00:04, 196.99it/s]

Prednisone
Prednisone
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Prednisone

process Case node:  17%|███▌                 | 152/902 [00:00<00:04, 170.99it/s]

Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc

process Case node:  24%|█████                | 216/902 [00:01<00:04, 140.79it/s]

Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Prednisone

process Case node:  29%|██████               | 258/902 [00:01<00:05, 115.42it/s]

Prednisone

process Case node:  32%|██████▋              | 286/902 [00:02<00:05, 111.60it/s]

Anakinra + Zinc
Prednisone
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc

process Case node:  36%|███████▋             | 329/902 [00:02<00:04, 130.20it/s]

Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc

process Case node:  46%|█████████▊           | 419/902 [00:02<00:02, 161.89it/s]

Prednisone
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone

process Case node:  54%|███████████▎         | 488/902 [00:03<00:03, 129.48it/s]

Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Anakinra + Zinc

process Case node:  57%|████████████         | 516/902 [00:03<00:03, 105.18it/s]

Anakinra + Zinc
Prednisone
Prednisone

process Case node:  64%|█████████████▍       | 576/902 [00:04<00:02, 118.94it/s]

Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc

process Case node:  67%|█████████████▉       | 601/902 [00:04<00:02, 109.60it/s]

Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc

process Case node:  70%|██████████████▋      | 630/902 [00:04<00:02, 117.53it/s]

Prednisone
Prednisone

process Case node:  76%|███████████████▉     | 682/902 [00:05<00:01, 113.37it/s]

Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Prednisone
Prednisone
Prednisone
Prednisone
Anakinra + Zinc

process Case node:  80%|████████████████▊    | 723/902 [00:05<00:01, 125.79it/s]

Prednisone
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc

process Case node:  92%|███████████████████▎ | 828/902 [00:06<00:00, 166.26it/s]

Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc
Prednisone
Anakinra + Zinc
Prednisone
Prednisone
Anakinra + Zinc

process Case node:  96%|████████████████████▏| 865/902 [00:06<00:00, 160.63it/s]

Prednisone
Anakinra + Zinc
Prednisone

process Case node: 100%|█████████████████████| 902/902 [00:06<00:00, 136.89it/s]

In [151]:
for index,row in tqdm(case_node.iterrows(),total=case_node.shape[0],desc="Cleaning Case node"):
    if row.aki_status == 'yes':
        case_node.at[index,'aki_status'] = 'Yes'
    if row.aki_status == 'no':
        case_node.at[index,'aki_status'] = 'No'
    if 'Healthy donor' in row.cohort:
        case_node.at[index,'cohort'] = 'Healthy Donor'
    if 'Heavy drinker with alcoholic hepatitis' in row.cohort:
        case_node.at[index,'cohort'] = 'Heavy Drinker with Alcoholic Hepatits'
    if 'Heavy drinker without alcoholic hepatitis' in row.cohort:
        case_node.at[index,'cohort'] = 'Heavy Drinker without Alcoholic Hepatits'
    if row.rct_meld_strata == 'High (>25)':
        case_node.at[index,'rct_meld_strata'] = 'High(>25)'
    if row.rct_meld_strata == 'Low (<=25)':
        case_node.at[index,'rct_meld_strata'] = 'Low(<=25)'

Cleaning Case node: 100%|███████████████████| 902/902 [00:00<00:00, 3931.98it/s]

In [152]:
#output the case node
case_node_path = os.path.join(OUT_PATH, 'case_node.tsv')
case_node.to_csv(case_node_path, sep = '\t', index =False)
case_node

,*type,project_id,*submitter_id,*studies.submitter_id,actarm,ah_hosp,ah_hosp_num,aki_status,bari_surgery,cohort,...,days_90_aki,days_90_survival,days_to_aki,days_to_consent,days_to_death,index_date,inf_cnst_sign_dt,rct_meld_strata,study_site,vital_status
0,case,ardac-p1031,11001_obs,obs,,,,Unknown,,Healthy Donor,...,Unknown,Unknown,None,,None,Study Enrollment,,,Cleveland Clinic,alive
1,case,ardac-p1031,11002_obs,obs,,,,Unknown,,Healthy Donor,...,Unknown,Unknown,None,,None,Study Enrollment,,,Cleveland Clinic,alive
2,case,ardac-p1031,11003_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,...,Unknown,alive,None,,None,Study Enrollment,,,Cleveland Clinic,alive
3,case,ardac-p1031,11004_obs,obs,,,,Unknown,,Healthy Donor,...,Unknown,Unknown,None,,None,Study Enrollment,,,Cleveland Clinic,alive
4,case,ardac-p1031,11006_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,...,Unknown,alive,None,,100,Study Enrollment,,,Cleveland Clinic,dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,case,ardac-p1031,81149_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,...,Unknown,Unknown,None,,None,Study Enrollment,,,Virginia Commonwealth University,alive
898,case,ardac-p1031,81150_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,...,Unknown,Unknown,None,,None,Study Enrollment,,,Virginia Commonwealth University,alive
899,case,ardac-p1031,81151_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,...,Unknown,Unknown,None,,None,Study Enrollment,,,Virginia Commonwealth University,alive
900,case,ardac-p1031,81152_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,...,Unknown,Unknown,None,,None,Study Enrollment,,,Virginia Commonwealth University,alive
901,case,ardac-p1031,81153_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,...,Unknown,Unknown,None,,None,Study Enrollment,,,Virginia Commonwealth University,alive