In [1]:
import os
import pandas as pd
from tqdm import tqdm

In [2]:
OUT_PATH = 'nodes'
SCHEMAS = 'node_template/submission_follow_up_template.tsv'

In [3]:
#read the diagnosis node header
follow_up_pd = pd.read_csv(SCHEMAS, sep = '\t')
follow_up_pd.drop(index=follow_up_pd.index[0], 
        axis=0, 
        inplace=True)
follow_up_pd

Empty DataFrame
Columns: [*type, project_id, *submitter_id, cases.submitter_id, demographics.submitter_id, *days_to_follow_up, admission_date, ascites_culture, ascites_culture_result, ascites_date, ascites_diagnosis_date, ascites_organism, bariatric_surgery, blood_culture, blood_culture_date, blood_culture_result, blood_organism, bmi, cdc_hiv_risk_factors, child_pugh_score, ct_date, ct_result, ct_result_finding, ct_result_sig, duodenum_ulcer_bleed, duodenum_ulcer_size, endoscopy, endoscopy_date, endoscopy_ulcer_present, endoscopy_varices_present, esophageal_ulcer_bleed, esophageal_ulcer_size, esophageal_varices_bleed, esophageal_varices_size, fibro_capmed, fibro_e, fibro_iqr, fibro_probe, fibro_total_number, fibroscan, fibroscan_date, firbro_e_iqr, firbro_valid_number, gastric_ulcer_bleed, gastric_ulcer_size, gastric_varices_bleed, gastric_varices_size, height, hep_carcinoma, hep_enceph, hep_enceph_diagnosis_date, hepcar_diagnosis_date, hospitalized_alc_hep, hospitalized_alc_hep_times, hospitalized_at_enrollment, infection_screen_date, infection_screen_done, lille_score, liver_abdomen_imaging, liver_imaging_type, liver_score_collected, liver_score_date, liver_transplant, liver_transplant_date, maddreys_score, medical_info_collected, meld_score, mri_date, mri_finding, mri_result, mri_sig, other_imaging_date, other_imaging_finding, other_imaging_result, other_imaging_sig, other_imaging_type, portal_hypertensive_gastropathy, soc_collected, stool_test, stool_test_date, stool_test_finding, tlfb_collected, tlfb_drinking_days, tlfb_number_drinks, ultrasound_date, ultrasound_finding, ultrasound_result, ultrasound_result_sig, urine_culture, urine_culture_date, urine_culture_fungal_result, urine_culture_organism, urine_culture_result, varices, varices_diagnosis_date, visit_day, weight, xray, xray_date, xray_findings, ...]
Index: []

[0 rows x 105 columns]

In [4]:
#Read case node data
case_node_pd = pd.read_csv('nodes/case_node.tsv', sep = '\t')
case_node_pd = case_node_pd.iloc[: , 1:]
case_node_pd

,project_id,*submitter_id,*studies.submitter_id,actarm,ah_hosp,ah_hosp_num,aki_status,bari_surgery,cohort,consent_type,...,days_90_aki,days_90_survival,days_to_aki,days_to_consent,days_to_death,index_date,inf_cnst_sign_dt,rct_meld_strata,study_site,vital_status
0,ardac-p1031,11001_obs,obs,,,,Unknown,,Healthy Donor,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Cleveland Clinic,alive
1,ardac-p1031,11002_obs,obs,,,,Unknown,,Healthy Donor,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Cleveland Clinic,alive
2,ardac-p1031,11003_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,,...,Unknown,alive,NaN,,NaN,Study Enrollment,,,Cleveland Clinic,alive
3,ardac-p1031,11004_obs,obs,,,,Unknown,,Healthy Donor,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Cleveland Clinic,alive
4,ardac-p1031,11006_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,,...,Unknown,alive,NaN,,100.0,Study Enrollment,,,Cleveland Clinic,dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,ardac-p1031,81149_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Virginia Commonwealth University,alive
898,ardac-p1031,81150_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Virginia Commonwealth University,alive
899,ardac-p1031,81151_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Virginia Commonwealth University,alive
900,ardac-p1031,81152_obs,obs,,,,Unknown,,Heavy Drinker with Alcoholic Hepatits,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Virginia Commonwealth University,alive
901,ardac-p1031,81153_obs,obs,,,,Unknown,,Heavy Drinker without Alcoholic Hepatits,,...,Unknown,Unknown,NaN,,NaN,Study Enrollment,,,Virginia Commonwealth University,alive

In [5]:
visit_pd = pd.read_csv('csv_datasets/VISIT.csv')
visit_pd

/var/folders/t6/whxvfv6s34b1fqcrw4x5_9mw0000gn/T/ipykernel_10490/842995263.py:1: DtypeWarning: Columns (16,54,55,163,241) have mixed types. Specify dtype option on import or set low_memory=False.
  visit_pd = pd.read_csv('csv_datasets/VISIT.csv')

,usubjid,site,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,visitnd,missed_visit,missed_visit_oth,visitdat,v0eqscreenv,...,cldq25,cldq26,cldq27,cldq28,cldq29,lilleday7,melddiff,cpsdiff,mdfdiff,visit_complete
0,11001,Cleveland Clinic,Week 0,NaN,NaN,NaN,NaN,NaN,2019-05-21,NaN,...,7. None of the time,7. None of the time,7. None of the time,7. None of the time,7. None of the time,0.0,0.0,0.0,0.0,Complete
1,11002,Cleveland Clinic,Week 0,NaN,NaN,NaN,NaN,NaN,2019-05-21,NaN,...,7. None of the time,7. None of the time,7. None of the time,7. None of the time,7. None of the time,0.0,0.0,0.0,0.0,Complete
2,11003,Cleveland Clinic,Week 0,NaN,NaN,NaN,NaN,NaN,2019-05-24,NaN,...,2. Most of the time,4.Some of the time,2. Most of the time,2. Most of the time,4.Some of the time,0.0,0.0,0.0,0.0,Complete
3,11003,Cleveland Clinic,Week 4,NaN,NaN,In person,NaN,NaN,2019-06-27,NaN,...,1. All of the time,2. Most of the time,5. A little of the time,1. All of the time,1. All of the time,0.0,0.0,0.0,0.0,Complete
4,11003,Cleveland Clinic,Week 12,NaN,NaN,Medical Record follow-up(Missed Visit),NaN,NaN,2019-09-20,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3005,81149,Virginia Commonwealth University,Week 0,NaN,NaN,NaN,NaN,NaN,2022-08-26,NaN,...,1. All of the time,1. All of the time,6. Hardly any of the time,3. A good bit of the time,6. Hardly any of the time,0.0,0.0,0.0,0.0,Complete
3006,81150,Virginia Commonwealth University,Week 0,NaN,NaN,NaN,NaN,NaN,2022-08-31,NaN,...,2. Most of the time,7. None of the time,7. None of the time,1. All of the time,7. None of the time,0.0,0.0,0.0,0.0,Complete
3007,81151,Virginia Commonwealth University,Week 0,NaN,NaN,NaN,NaN,NaN,2022-09-14,NaN,...,1. All of the time,1. All of the time,7. None of the time,1. All of the time,1. All of the time,0.0,0.0,0.0,0.0,Complete
3008,81152,Virginia Commonwealth University,Week 0,NaN,NaN,NaN,NaN,NaN,2022-09-16,NaN,...,7. None of the time,2. Most of the time,6. Hardly any of the time,5. A little of the time,6. Hardly any of the time,0.0,0.0,0.0,0.0,Complete
3009,81153,Virginia Commonwealth University,Week 0,NaN,NaN,NaN,NaN,NaN,2022-09-21,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Complete

In [6]:
#calculate the redcap_event_name time
def get_redcap_event_name(value):
    if 'Week' in value:
        to_day = int(value.split(' ')[-1]) * 7
        #print('Week_to_day: ', to_day)
        return to_day
    if 'Day' in value:
        to_day = int(value.split(' ')[-1]) * 1
        #print('Day_to_day: ', to_day)
        return to_day
    if 'Screening' in value:
        to_day = -1
        #print('Screening_to_day: ', to_day)
        return to_day
    
    ##need to be clarify
    if 'Medical Record Follow-up Arm' in value:
        #record_to_day = int(value.split(' ')[-1]) * 9999
        to_day = -1
        #print('Medical_Record_to_day: ', -1)
        return to_day

def get_cps(value):
    if value == 999:
        return None
    elif value == None:
        return 0
    else:
        return value

def row_init(len):
    row = [None]*len
    return row

def set_column_value(df, col_name, row, value):
    index= df.columns.get_loc(col_name)
    row[index] = value
    return row

In [7]:
for index,row in tqdm(visit_pd.iterrows(),total=visit_pd.shape[0],desc="process Follow_up node"):
    #general properies for both observation and clinical trial study
    follow_up_type = 'follow_up'
    project_id = 'ardac-p1031'
    
    #map case.submitter.id
    case_submitter_id = row.usubjid
    for index_case,row_case in case_node_pd.iterrows():
        if str(case_submitter_id) in str(row_case['*submitter_id']):
            case_submitter_id = str(row_case['*submitter_id'])
            break
        
    
    days_to_follow_up = get_redcap_event_name(row.redcap_event_name)
    submitter_id = str(case_submitter_id) + '_' + str(days_to_follow_up)
    bmi = row.bmi
    #if cps = blank, should I assign 0 ?
    child_pugh_score = get_cps(row.cps)
    lille_score = row.lille
    maddreys_score = row.mdf
    meld_score = row.meld
    
    
    #Assign the value in to the follow up node
    follow_up_row = row_init(len(follow_up_pd.axes[1]))
    follow_up_row = set_column_value(follow_up_pd, '*type', follow_up_row, follow_up_type)
    follow_up_row = set_column_value(follow_up_pd, 'project_id', follow_up_row, project_id)
    follow_up_row = set_column_value(follow_up_pd, '*submitter_id', follow_up_row, submitter_id)
    follow_up_row = set_column_value(follow_up_pd, 'cases.submitter_id', follow_up_row, case_submitter_id)
    follow_up_row = set_column_value(follow_up_pd, '*days_to_follow_up', follow_up_row, days_to_follow_up)
    follow_up_row = set_column_value(follow_up_pd, 'bmi', follow_up_row, bmi)
    follow_up_row = set_column_value(follow_up_pd, 'child_pugh_score', follow_up_row, child_pugh_score)
    follow_up_row = set_column_value(follow_up_pd, 'lille_score', follow_up_row, lille_score)
    follow_up_row = set_column_value(follow_up_pd, 'maddreys_score', follow_up_row, maddreys_score)
    follow_up_row = set_column_value(follow_up_pd, 'meld_score', follow_up_row, meld_score)
    follow_up_row = set_column_value(follow_up_pd, 'visit_day', follow_up_row, days_to_follow_up)
    
    
    follow_up_pd.loc[len(follow_up_pd.index)] = follow_up_row

process Follow_up node: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3010/3010 [01:46<00:00, 28.23it/s]

In [8]:
follow_up_pd.drop(follow_up_pd[follow_up_pd['*days_to_follow_up'] == -1].index, inplace = True)
follow_up_pd

,*type,project_id,*submitter_id,cases.submitter_id,demographics.submitter_id,*days_to_follow_up,admission_date,ascites_culture,ascites_culture_result,ascites_date,...,visit_day,weight,xray,xray_date,xray_findings,xray_impression,xray_infiltrates,xray_last_4_weeks,xray_normal,xray_pleural_effusion
0,follow_up,ardac-p1031,11001_obs_0,11001_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
1,follow_up,ardac-p1031,11002_obs_0,11002_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
2,follow_up,ardac-p1031,11003_obs_0,11003_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3,follow_up,ardac-p1031,11003_obs_28,11003_obs,None,28,None,None,None,None,...,28,None,None,None,None,None,None,None,None,None
4,follow_up,ardac-p1031,11003_obs_84,11003_obs,None,84,None,None,None,None,...,84,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3005,follow_up,ardac-p1031,81149_obs_0,81149_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3006,follow_up,ardac-p1031,81150_obs_0,81150_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3007,follow_up,ardac-p1031,81151_obs_0,81151_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3008,follow_up,ardac-p1031,81152_obs_0,81152_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3009,follow_up,ardac-p1031,81153_obs_0,81153_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None

In [ ]:
for index,row in tqdm(follow_up_pd.iterrows(),total=follow_up_pd.shape[0],desc="Cleaning Follow Up Node"):
    if row.meld_score == 999 or row.meld_score == 0:
        follow_up_pd.at[index,'meld_score'] = np.nan
    if row.lille_score == 999 or row.lille_score == 0:
        follow_up_pd.at[index,'lille_score'] = np.nan

In [10]:
#output the follow up node
follow_up_node_path = os.path.join(OUT_PATH, 'follow_up_node.tsv')
follow_up_pd.to_csv(follow_up_node_path, sep = '\t', index=False)
follow_up_pd

,*type,project_id,*submitter_id,cases.submitter_id,demographics.submitter_id,*days_to_follow_up,admission_date,ascites_culture,ascites_culture_result,ascites_date,...,visit_day,weight,xray,xray_date,xray_findings,xray_impression,xray_infiltrates,xray_last_4_weeks,xray_normal,xray_pleural_effusion
0,follow_up,ardac-p1031,11001_obs_0,11001_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
1,follow_up,ardac-p1031,11002_obs_0,11002_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
2,follow_up,ardac-p1031,11003_obs_0,11003_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3,follow_up,ardac-p1031,11003_obs_28,11003_obs,None,28,None,None,None,None,...,28,None,None,None,None,None,None,None,None,None
4,follow_up,ardac-p1031,11003_obs_84,11003_obs,None,84,None,None,None,None,...,84,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3005,follow_up,ardac-p1031,81149_obs_0,81149_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3006,follow_up,ardac-p1031,81150_obs_0,81150_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3007,follow_up,ardac-p1031,81151_obs_0,81151_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3008,follow_up,ardac-p1031,81152_obs_0,81152_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None
3009,follow_up,ardac-p1031,81153_obs_0,81153_obs,None,0,None,None,None,None,...,0,None,None,None,None,None,None,None,None,None